name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VM and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" mykey
          chmod 600 mykey
          ssh -o StrictHostKeyChecking=no -i mykey w_chess-good_28a135e1@81.177.174.12 'EOF'
            cd /home/virtwww/w_chess-good_28a135e1/http
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            git pull origin main
            sudo docker build -t myapp .
            sudo docker run -d -p 3000:3000 --name myapp myapp
          EOF
