name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'miami7777/chess-good'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
     - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      run: docker build -t app . --file Dockerfile --tag my-image-name:$(date +%s)
    
 