name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
     - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      run: docker build -t app . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Save Docker image as tarball
      run: docker save app -o app.tar

    - name: Verify tarball exists
      run: ls -lh app.tar
      
    - name: Change file permissions
      run: chmod 644 app.tar

    - name: SSH to VPS and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          docker load -i /home/${{ secrets.VPS_USER }}/app.tar
          if [ "$(docker ps -q -f name=app)" ]; then
            docker stop app
          fi
          if [ "$(docker ps -a -q -f name=app)" ]; then
            docker rm app
          fi
          docker run --name app -p 5144:8080 -d app
       